// Generated by CoffeeScript 1.7.1
(function() {
  var cli, help, nopt, path, server, utils, _;

  path = require("path");

  _ = require("underscore");

  nopt = require("nopt");

  utils = require("./utils");

  server = require("./server");

  cli = exports;

  cli.main = function(args) {
    var defValue, defValues, longOpts, name, opt, opts, parsed, shortName, shortOpts, type, _ref;
    if ((_ref = args[0]) === "?" || _ref === "-?" || _ref === "--?") {
      help();
    }
    opts = {
      verbose: ["v", Boolean],
      help: ["h", Boolean]
    };
    longOpts = {};
    shortOpts = {};
    defValues = {};
    for (name in opts) {
      opt = opts[name];
      shortName = opt[0], type = opt[1], defValue = opt[2];
      if (type === Boolean) {
        defValue = false;
      }
      shortOpts[shortName] = "--" + name;
      longOpts[name] = type;
      if (defValue != null) {
        defValues[name] = defValue;
      }
    }
    parsed = nopt(longOpts, shortOpts, args, 0);
    if (parsed.help) {
      help();
    }
    args = parsed.argv.remain;
    opts = _.pick(parsed, _.keys(longOpts));
    opts = _.defaults(opts, defValues);
    utils.verbose(opts.verbose);
    return server.main(args, opts);
  };

  help = function() {
    console.log("" + utils.PROGRAM + "\n\nusage:\n\n  " + utils.PROGRAM + " [options]\n\noptions:\n\n  -v --verbose        generate diagnostic messages\n\nRuns a web server on your local development box, which will display\ncf logs for all your things.\n\nversion: " + utils.VERSION + "; for more info: " + utils.HOMEPAGE);
    return process.exit(1);
  };

  if (require.main === module) {
    cli.main.call(null, process.argv.slice(2));
  }

}).call(this);
