// Generated by CoffeeScript 1.7.1
(function() {
  var express, fs, handleMessages, messages, path, ports, sendMessages, server, utils;

  fs = require("fs");

  path = require("path");

  ports = require("ports");

  express = require("express");

  utils = require("./utils");

  messages = require("./messages");

  server = exports;

  server.main = function(args, opts) {
    var app, port, wwwPath;
    port = ports.getPort(utils.PROGRAM);
    app = express();
    wwwPath = path.join(__dirname, "..", "www");
    app.get("/api/messages", handleMessages);
    app.use(express["static"](wwwPath));
    app.listen(port, "localhost", function() {
      return utils.log("server starting on http://localhost:" + port);
    });
    return setInterval(sendMessages, 1000);
  };

  sendMessages = function() {};

  handleMessages = function(request, response) {
    return messages.handleHttpRequest(request, response);
  };

}).call(this);
